Produk:
    type: object
    properties:
        id_produk: { type: integer }
        nama_produk: { type: string }
        deskripsi: { type: string }
        harga: { type: integer }
        estimasi_pengerjaan: { type: integer }
        bahan: { type: string }
        foto: { type: string }
        created_at:
            type: string
            format: date-time
